### ISSUE TITLE
Apple Silicon is currently not supported

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-nodejs#358]
⚠️ **Note for our users:** For the time being, Apple Silicon is not supported natively by this integration or any of our other integrations.

See https://github.com/appsignal/appsignal-elixir/issues/615#issuecomment-755385788 for more information.

**Comment by tombruijn** [comment]
Support has been added for this in the latest 1.3.1 release of the nodejs package. Please let us know if it works here, or at support@appsignal.com with a [diagnose report](https://docs.appsignal.com/nodejs/command-line/diagnose.html).

Closing the issue now. We can reopen it if new issues arise.

**Comment by Manduro** [comment]
Running on M1 I get the following error:

```
AppSignal extension not loaded. This could mean that your current environment isn't supported, or that another error has occurred.
```

Looking a bit deeper I noticed that the `@appsignal/nodejs-ext` package is not installed. This seems to be happening due to its specified `cpu` requirements, from `package-lock.json`:

```
"node_modules/@appsignal/nodejs-ext": {
      "version": "2.0.7",
      "resolved": "https://registry.npmjs.org/@appsignal/nodejs-ext/-/nodejs-ext-2.0.7.tgz",
      "integrity": "sha512-3m0kh486fCNJ0B+FVCIxRTshE73vRTPtTyazPxGZSPNT5bk14DTjTBRrJiGyXIMvxFNB8ROI2iPM5txINTtoBQ==",
      "cpu": [
        "x64",
        "x86"
      ],
      "hasInstallScript": true,
      "optional": true,
      "os": [
        "linux",
        "darwin",
        "freebsd"
      ],
      "dependencies": {
        "node-addon-api": "^3.1.0",
        "node-gyp": "^7.1.2"
      },
      "engines": {
        "node": ">= 12"
      }
    },
```

Diagnose report:

```
npx @appsignal/cli diagnose
🔭 Checking your package.json for @appsignal/nodejs...
✅ Found it! Running the diagnose tool...
AppSignal extension not loaded. This could mean that your current environment isn't supported, or that another error has occurred.
/pathtomyproject/node_modules/@appsignal/nodejs/dist/extension.js:68
        return extension_wrapper_1.extension.runningInContainer();
                                             ^

TypeError: extension_wrapper_1.extension.runningInContainer is not a function
    at Extension.runningInContainer (/pathtomyproject/node_modules/@appsignal/nodejs/dist/extension.js:68:46)
    at DiagnoseTool.getHostData (/pathtomyproject/node_modules/@appsignal/nodejs/dist/diagnose.js:64:84)
    at DiagnoseTool.generate (/pathtomyproject/node_modules/@appsignal/nodejs/dist/diagnose.js:35:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Diagnose.run (/pathtomyproject/node_modules/@appsignal/nodejs/dist/cli/diagnose.js:18:22)
```

**Comment by tombruijn** [comment]
Hi @Manduro, are you running the app through Rosetta 2 or directly on on the ARM architecture?

The issue with the diagnose report is fixed in PR #557 and will be included in the next release. We may need the report from that version once it's out.

Related internal issue: https://github.com/appsignal/appsignal-agent/issues/733 (private link)

**Comment by Manduro** [comment]
Everything is running directly on ARM without Rosetta 2.

I'm happy to report back with a new diagnose report when it's fixed.

**Comment by Manduro** [comment]
I applied the diagnose fix locally and now get the following output:

```
> npx @appsignal/cli diagnose
🔭 Checking your package.json for @appsignal/nodejs...
✅ Found it! Running the diagnose tool...
AppSignal extension not loaded. This could mean that your current environment isn't supported, or that another error has occurred.
AppSignal diagnose
================================================================================
Use this information to debug your configuration.
More information is available on the documentation site.
https://docs.appsignal.com/
Send this output to support@appsignal.com if you need help.
================================================================================

AppSignal library
	Language: Node.js
	Package version: '2.2.10'
	Agent version: '15ee07b'
	Extension loaded: false

Extension installation report
	Error found while parsing the report.
	Error: Error: ENOENT: no such file or directory, open '/tmp/appsignal-895e2005cea155bd44acd0af1539604dad59975ff9581d2b6fe3e214ecf4adb9-install.report'

Host information
	Architecture: 'arm64'
	Operating System: 'darwin'
	Node.js version: '16.13.1'
	Root user: false
	Running in container: undefined

Agent diagnostics
	Extension tests
		Configuration: -
	Agent tests
		Started: -
		Process user id: -
		Process user group id: -
		Configuration: -
		Logger: -
		Working directory user id: -
		Working directory user group id: -
		Working directory permissions: -
		Lock path: -

Configuration
	active: true (Loaded from: initial)
	caFilePath: '/pathtomyproject/node_modules/@appsignal/nodejs/cert/cacert.pem'
	debug: false
	dnsServers: []
	enableHostMetrics: true
	enableMinutelyProbes: true
	enableStatsd: false
	endpoint: 'https://push.appsignal.com'
	environment: 'development'
	filesWorldAccessible: true
	filterParameters: []
	filterSessionData: []
	ignoreActions: []
	ignoreErrors: []
	ignoreNamespaces: []
	log: 'file'
	pushApiKey: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' (Loaded from: env)
	requestHeaders: ["accept","accept-charset","accept-encoding","accept-language","cache-control","connection","content-length","range"]
	sendEnvironmentMetadata: true
	sendParams: true
	sendSessionData: true
	transactionDebugMode: false

Read more about how the diagnose config output is rendered
https://docs.appsignal.com/nodejs/command-line/diagnose.html

Validation
	Validating Push API key: valid

Paths
	Current working directory
		Path: '/pathtomyproject'

	Log directory
		Path: '/tmp'

	AppSignal log
		Path: '/tmp/appsignal.log'
		Contents (last 10 lines):


Diagnostics report
	Do you want to send this diagnostics report to AppSignal?
	If you share this report you will be given a link to
	AppSignal.com to validate the report.
	You can also contact us at support@appsignal.com
	with your support token.

	Send diagnostics report to AppSignal? (Y/n): Y
	Not sending diagnostics information to AppSignal.
```

An interesting bit is that I answered `Y` to send the report, to which it replies 'Not sending' 🤔

**Comment by tombruijn** [comment]
For some reason the install report is not found in the report. Do you see any files in the system `/tmp/` dir that follow this format? `appsignal-<HASH>-install.report`?

> An interesting bit is that I answered Y to send the report, to which it replies 'Not sending' 🤔

That is weird. I'll test if that's not broken.

**Comment by tombruijn** [comment]
Aha that might explain it. We've since added it to the package: https://github.com/appsignal/appsignal-nodejs/blob/6ff9eec3fdba78d8c3d54605f503e37a8f328da8/packages/nodejs/package.json#L47
(The nodejs-ext package is now merged into the main "nodejs" package.)

That change is, you might have guessed it, planned for the next release.

**Comment by Manduro** [comment]
Nice, thanks! Although for Apple's M1 it should probably be `arm64` instead of `arm`?

**Comment by tombruijn** [comment]
Probably should be "arm64" yes. That's what we follow in our install script: https://github.com/appsignal/appsignal-nodejs/blob/6392d2ff9c6c98cca4c08c0f0b8eda0bf038946b/packages/nodejs/scripts/extension/extension.js#L132-L133

I created an issue figuring this out in #560

**Comment by tombruijn** [comment]
@Manduro I've just published nodejs package 2.3.0. Can you upgrade and let us know if that helps fix the ARM install issue and the diagnose report?

**Comment by Manduro** [comment]
@tombruijn Everything seems fixed, thanks a lot.

```
> npx @appsignal/cli diagnose
🔭 Checking your package.json for @appsignal/nodejs...
✅ Found it! Running the diagnose tool...
AppSignal diagnose
================================================================================
Use this information to debug your configuration.
More information is available on the documentation site.
https://docs.appsignal.com/
Send this output to support@appsignal.com if you need help.
================================================================================

AppSignal library
	Language: Node.js
	Package version: '2.3.0'
	Agent version: '15ee07b'
	Extension loaded: true

Extension installation report
	Installation result
		Status: success
	Language details
		Node.js version: '16.13.1'
	Download details
		Download URL: 'https:/appsignal-agent-releases.global.ssl.fastly.net/15ee07b/appsignal-aarch64-darwin-all-static.tar.gz'
		Checksum: 'verified'
	Build details
		Install time: '2022-01-20T14:54:51.554Z'
		Architecture: 'arm64'
		Target: 'darwin'
		Musl override: false
		Linux ARM override: false
		Library type: 'static'
		Dependencies: {}
		Flags: {}
	Host details
		Root user: false
		Dependencies: {}

Host information
	Architecture: 'arm64'
	Operating System: 'darwin'
	Node.js version: '16.13.1'
	Root user: false
	Running in container: false

Agent diagnostics
	Extension tests
		Configuration: valid
	Agent tests
		Started: started
		Process user id: 501
		Process user group id: 20
		Configuration: valid
		Logger: started
		Working directory user id: 501
		Working directory user group id: 0
		Working directory permissions: 16895
		Lock path: writable

Configuration
	active: false
	caFilePath: '/pathtomyproject/node_modules/@appsignal/nodejs/cert/cacert.pem'
	debug: false
	dnsServers: []
	enableHostMetrics: true
	enableMinutelyProbes: true
	enableStatsd: false
	endpoint: 'https://push.appsignal.com'
	environment: 'development'
	filesWorldAccessible: true
	filterParameters: []
	filterSessionData: []
	ignoreActions: []
	ignoreErrors: []
	ignoreNamespaces: []
	log: 'file'
	pushApiKey: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' (Loaded from: env)
	requestHeaders: ["accept","accept-charset","accept-encoding","accept-language","cache-control","connection","content-length","range"]
	sendEnvironmentMetadata: true
	sendParams: true
	sendSessionData: true
	transactionDebugMode: false

Read more about how the diagnose config output is rendered
https://docs.appsignal.com/nodejs/command-line/diagnose.html

Validation
	Validating Push API key: valid

Paths
	Current working directory
		Path: '/Users/job/Git/backend'

	Log directory
		Path: '/tmp'

	AppSignal log
		Path: '/tmp/appsignal.log'
		Contents (last 10 lines):
```

**Comment by tombruijn** [comment]
@Manduro Great to hear it's working! Then I'm closing the issue again.
