### ISSUE TITLE
Diagnose that can't read the install report will fail

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#448]
We've seen a user be unable to load the installation and submit the diagnose report: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700063450

The Node.js integration doesn't handle not being able to load the install report. It should report an error state like in the Ruby gem: https://github.com/appsignal/appsignal-ruby/blob/0f984d851debffc2b186dc47ceeca1662b419352/lib/appsignal/cli/diagnose.rb#L336-L348

but instead it replaces it with an empty object: https://github.com/appsignal/appsignal-nodejs/blob/ad40d9d8ec0dcedb38973339d75a18373eb7d3ef/packages/nodejs/src/diagnose.ts#L91

Which will cause an error when nested keys are fetched: https://github.com/appsignal/appsignal-nodejs/blob/ad40d9d8ec0dcedb38973339d75a18373eb7d3ef/packages/nodejs/src/cli/diagnose.ts#L41

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700064306

**Comment by shairyar** [comment]
Adding it here in case it is helpful while working on the diagnose report

```
During the node modules installation following error occured while building @appsignal/nodejs-ext extension:

[4/4] Building fresh packages...
warning Error running install script for optional dependency: "/tmp/build_f6b6088e/node_modules/@appsignal/nodejs-ext: Command failed.
Exit code: 1
Command: node scripts/extension.js
Arguments:
Directory: /tmp/build_f6b6088e/node_modules/@appsignal/nodejs-ext
Output:
Error: Checksum verification failed
at Hash.<anonymous> (/tmp/build_f6b6088e/node_modules/@appsignal/nodejs-ext/scripts/extension.js:68:25)
at Hash.emit (events.js:387:35)
at finish (internal/streams/writable.js:657:10)
at processTicksAndRejections (internal/process/task_queues.js:82:21)"
info This module is OPTIONAL, you can safely ignore this error
Done in 36.32s.
```
