### ISSUE TITLE
Extension function calls safety

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#556]
When the extension fails to install, or has been installed for a not matching architecture, function calls to the extension may fail.

For example, when running the macOS build on a Linux docker image, calling the diagnose function results in the following:

```
$ npx @appsignal/cli diagnose
🔭 Checking your package.json for @appsignal/nodejs...
✅ Found it! Running the diagnose tool...
AppSignal extension not loaded. This could mean that your current environment isn't supported, or that another error has occurred. // This is no longer present after PR #554 
/integration/packages/nodejs/dist/extension.js:68
        return extension_wrapper_1.extension.runningInContainer();
                                             ^

TypeError: extension_wrapper_1.extension.runningInContainer is not a function
    at Extension.runningInContainer (/integration/packages/nodejs/dist/extension.js:68:46)
    at DiagnoseTool.getHostData (/integration/packages/nodejs/dist/diagnose.js:64:84)
    at DiagnoseTool.generate (/integration/packages/nodejs/dist/diagnose.js:35:24)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Diagnose.run (/integration/packages/nodejs/dist/cli/diagnose.js:18:22)
```
(Example run on the main branch before PR #554 is merged. https://github.com/appsignal/appsignal-nodejs/commit/58f1ae0b5ed62f9a92c736515a2efb2b5d2859da)

This shouldn't happen. It shouldn't cause an error.

When the extension module is not present it should not call functions that may fail.

**Comment by tombruijn** [comment]
The Node.js integration doesn't impelement "noop" functions for _all extension functions_ like the other integrations do. That may be a safer way to solve this issue, and doesn't require checks wherever we call the extension functions.

Creating a `NoopExtension` class that gets initialized from the [extension wrapper](https://github.com/appsignal/appsignal-nodejs/blob/3ce0e21e72a80c0a397aa28ee98ae4f33fa20250/packages/nodejs/src/extension_wrapper.ts#L9-L19) when the extension fails to load may be a good solution here.

**Comment by tombruijn** [comment]
I need to check all the places these attributes on the ExtensionWrapper can get called. The extension wrapper seems to be the most direct way to interact with the extension.

https://github.com/appsignal/appsignal-nodejs/blob/cd9b2efa8c65331a0b3d9d83bfce181493dd7b5b/packages/nodejs/src/interfaces/extension_wrapper.ts#L3-L7

It looks like the Span extension interaction is all hidden away through noop objects if it's not available. It's different than what I'm used to from the Elixir and Ruby integrations, where we stub out the extension functions and leave all the other functionality intact. It now is is a little difficult to follow sometimes what the data flow is, when the extension isn't loaded.

We can choose to remove all the noop objects in favor of only stubbing out the extension functions if that's easier.

---

My journey notes so far:

The BaseSpan object is the only thing that interacts with the "span" extension class. Which we then have to rely on, that nothing calls that BaseSpan ever, if the extension is not loaded.

https://github.com/appsignal/appsignal-nodejs/blob/cd9b2efa8c65331a0b3d9d83bfce181493dd7b5b/packages/nodejs/src/span.ts#L5

If the extension isn't loaded, it will return `NoopSpan`s, because it will [return the `NoopTracer`](https://github.com/appsignal/appsignal-nodejs/blob/cd9b2efa8c65331a0b3d9d83bfce181493dd7b5b/packages/nodejs/src/client.ts#L113-L115).

It can return "NoopSpan"s here if no (root) span is currently active.

https://github.com/appsignal/appsignal-nodejs/blob/cd9b2efa8c65331a0b3d9d83bfce181493dd7b5b/packages/nodejs/src/tracer.ts#L61

This check reads a little weird. It uses the noopspan as a nil check if no extension is present, while it's also used when the extension isn't loaded. We should rather ask "is there a root span? If no, create a new one". Move that behavior to the tracer or communicate it with another function call than like this.
https://github.com/appsignal/appsignal-nodejs/blob/main/packages/nodejs/src/instrumentation/http/lifecycle/outgoing.ts

**Comment by tombruijn** [comment]
I wanted to test a small refactor, taking out all the `Noop*` classes and letting the extension calls just do nothing. Like it's implemented in the Ruby and Elixir integrations. But I'm running into so many issues and having to write so many tests for things that should be, but currently are not, tested. I'm giving up on the project for now.

**Comment by tombruijn** [comment]
Created a separate issue to first improve test coverage before I can reliably try this refactor.
