### ISSUE TITLE
Error on `setFloat` for Data object

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#638]
In PR https://github.com/appsignal/appsignal-agent/pull/756, we ran into the issue that `setFloat` caused an error about an invalid argument. This happened in the [spec/integration/opentelemetry_spec.rb](https://github.com/appsignal/appsignal-agent/pull/756/files#diff-a16593e93a9506767a8e72ea2bfd038b254f1b916f50753855a205fadbecc7ab).

The attributes we set where the following:

```
{ "string": "example string", "bool": true, "int": 10, "double": 12.3 },
```

We should check if this is a bug in the C++ extension.

```
Runner #1
Sudo: false
Output:
DEPRECATED: File names are no longer supported in the 'logPath' config option. Changing the filename to 'appsignal.log'
DEPRECATED: File names are no longer supported in the 'logPath' config option. Changing the filename to 'appsignal.log'
/Users/tombruijn/appsignal/agent/integrations/appsignal-nodejs/packages/nodejs/dist/internal/data.js:32
                        extension_wrapper_1.datamap.setFloat(key, value, map);
                                                    ^

Error: Invalid argument
    at /Users/tombruijn/appsignal/agent/integrations/appsignal-nodejs/packages/nodejs/dist/internal/data.js:32:53
    at Array.forEach (<anonymous>)
    at Function.mapObject (/Users/tombruijn/appsignal/agent/integrations/appsignal-nodejs/packages/nodejs/dist/internal/data.js:22:36)
    at Function.generate (/Users/tombruijn/appsignal/agent/integrations/appsignal-nodejs/packages/nodejs/dist/internal/data.js:8:25)
    at Extension.importOpenTelemetrySpan (/Users/tombruijn/appsignal/agent/integrations/appsignal-nodejs/packages/nodejs/dist/extension.js:29:166)
    at BaseClient.importOpenTelemetrySpan (/Users/tombruijn/appsignal/agent/integrations/appsignal-nodejs/packages/nodejs/dist/client.js:123:24)
    at run (/Users/tombruijn/appsignal/agent/spec/integration/runners/nodejs/opentelemetry.js:31:13)
    at Object.<anonymous> (/Users/tombruijn/appsignal/agent/spec/integration/runners/nodejs/opentelemetry.js:46:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Comment by tombruijn** [comment]
@unflxw I've assigned you for now after what we discussed yesterday.
