### ISSUE TITLE
APPSIGNAL_APP_ENV is not respected

### ISSUE THREAD

**Issue by jtmkrueger** [appsignal/appsignal-nodejs#704]
### Description

Neither `APPSIGNAL_APP_ENV` or an environment key appears to be respected by the library and it still sends only to the value of `NODE_ENV`

### Expectation
```javascript
export const appsignal = new Appsignal({
  name: 'peggy',
  environment: process.env.PUBLIC_ENV || 'staging',
  ...
});
```
the above code would have appsignal send to either the env var `PUBLIC_ENV`'s value or `staging`

### Reality
Any setting of this or an `APPSIGNAL_APP_ENV` sends to whatever the value of `NODE_ENV` is set to.

**Comment by tombruijn** [comment]
Hi @jtmkrueger, We do listen for the `APPSIGNAL_APP_ENV` key, but it's in [a different load order than our other libraries](https://docs.appsignal.com/nodejs/configuration/load-order.html). Something we've been meaning to make more consistent. ([Internal link for the team.](https://github.com/appsignal/integration-guide/issues/73))

If you specify a value in the initializer, that value will be used, rather than the env var. 

By removing the config option from the initializer it will work:

```js
export const appsignal = new Appsignal({
  name: 'peggy'
  // ...
});
```

Or by specifying it to be the leading one:

```js
export const appsignal = new Appsignal({
  name: 'peggy',
  environment: process.env.APPSIGNAL_APP_ENV || process.env.PUBLIC_ENV || 'staging',
  // ...
});
```

**Comment by treemmett** [comment]
I am seeing a similar result.

```javascript
const appSignal = new Appsignal({
  environment: 'staging',
  name: 'my-app',
  pushApiKey: 'foo',
});
```

However, I only see `production` and `development` within my AppSignal account. I'm running @appsignal/nodejs@2.4.2

**Comment by tombruijn** [comment]
@treemmett can you add the [`active: true` option](https://docs.appsignal.com/nodejs/configuration/options.html#option-active) to your config? That should fix it.

**Comment by treemmett** [comment]
Yes, I have tried both `active: true` and `active: process.env.NODE_ENV === 'production'`, but neither options have resolved this issue

**Comment by tombruijn** [comment]
@treemmett can you send a diagnose report token our way at support@appsignal.com? We'll have a look at it on Monday.

Run this command from the host on which your staging app is running, and in the project's root directory:

```
npx @appsignal/cli diagnose --api-key="<PUSH API KEY HERE>" --environment=staging
```
Don't forget to confirm the prompt to send it our way.
Note that it won't read your app's config file so don't worry if the config doesn't matches. What I'm interested in is the logs included in the report.

**Comment by jtmkrueger** [comment]
Hey @tombruijn I ran that on a staging vm and it sent you a diagnostic report 👍

**Comment by tombruijn** [comment]
I haven't seen any new diagnose reports come in. Did it send successfully?

Do you still have your original problem after changing your config as per [my previous comment](https://github.com/appsignal/appsignal-nodejs/issues/704#issuecomment-1170860294)?

**Comment by jtmkrueger** [comment]
```$ npx @appsignal/cli diagnose --api-key="foo" --environment=staging
Need to install the following packages:
  @appsignal/cli
Ok to proceed? (y) y
🔭 Checking your package.json for @appsignal/nodejs...
✅ Found it!
AppSignal extension not loaded. This could mean that your current environment isn't supported, or that another error has occurred.
AppSignal diagnose
================================================================================
Use this information to debug your configuration.
More information is available on the documentation site.
https://docs.appsignal.com/
Send this output to support@appsignal.com if you need help.
================================================================================

AppSignal library
  Language: Node.js
  Package version: '2.4.2'
  Agent version: '1a8ac46'
  Extension loaded: false

Extension installation report
  Installation result
    Status: error
    Error: Command failed: node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.13.2 | linux | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is "/usr/bin/python"
gyp ERR! find Python - version is "2.7.16"
gyp ERR! find Python - version is 2.7.16 - should be >=3.6.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/app/node_modules/node-gyp/lib/find-python.js:330:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/app/node_modules/node-gyp/lib/find-python.js:159:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/app/node_modules/node-gyp/lib/find-python.js:266:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/app/node_modules/node-gyp/lib/find-python.js:297:7)
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:388:7)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
gyp ERR! System Linux 5.13.0-1031-azure
gyp ERR! command "/usr/local/bin/node" "/usr/app/node_modules/@appsignal/nodejs/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/app/node_modules/@appsignal/nodejs
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok

  Language details
    Node.js version: '16.13.2'
  Download details
    Download URL: 'https://appsignal-agent-releases.global.ssl.fastly.net/1a8ac46/appsignal-x86_64-linux-all-static.tar.gz'
    Checksum: 'verified'
  Build details
    Install time: '2022-07-01T13:47:24.599Z'
    Architecture: 'x64'
    Target: 'linux'
    Musl override: false
    Linux ARM override: false
    Library type: 'static'
    Dependencies: {}
    Flags: {}
  Host details
    Root user: true
    Dependencies: {}

Host information
  Architecture: 'x64'
  Operating System: 'linux'
  Node.js version: '16.13.2'
  Root user: true
  Running in container: undefined

  Error while parsing agent diagnostics report:
    Error: SyntaxError: Unexpected token u in JSON at position 0
    Output:

Configuration
  active: false
  caFilePath: '/usr/app/node_modules/@appsignal/nodejs/cert/cacert.pem'
  debug: false
  dnsServers: []
  enableHostMetrics: true
  enableMinutelyProbes: true
  enableStatsd: false
  endpoint: 'https://push.appsignal.com'
  environment: 'staging'
    Sources:
      default: 'production'
      env:     'staging'
  filesWorldAccessible: true
  filterParameters: []
  filterSessionData: []
  ignoreActions: []
  ignoreErrors: []
  ignoreNamespaces: []
  instrumentHttp: true
  instrumentPg: true
  instrumentRedis: true
  log: 'file'
  pushApiKey: 'foo' (Loaded from: env)
  requestHeaders: ["accept","accept-charset","accept-encoding","accept-language","cache-control","connection","content-length","range"]
  sendEnvironmentMetadata: true
  sendParams: true
  sendSessionData: true
  transactionDebugMode: false

Read more about how the diagnose config output is rendered
https://docs.appsignal.com/nodejs/command-line/diagnose.html

Validation
  Validating Push API key: valid

Paths
  Current working directory
    Path: '/usr/app'

  Log directory
    Path: '/tmp'

  AppSignal log
    Path: '/tmp/appsignal.log'
    Contents (last 10 lines):


Diagnostics report
  Do you want to send this diagnostics report to AppSignal?
  If you share this report you will be given a link to
  AppSignal.com to validate the report.
  You can also contact us at support@appsignal.com
  with your support token.

  Send diagnostics report to AppSignal? (Y/n): Y
  Not sending diagnostics information to AppSignal.
npm notice
npm notice New minor version of npm available! 8.1.2 -> 8.13.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.13.2
npm notice Run npm install -g npm@8.13.2 to update!
npm notice
```

I scrubbed the key @tombruijn

**Comment by tombruijn** [comment]
Ah I see the problem @jtmkrueger, please submit it using `y` (lowercase y) instead of `Y`. We're aware it doesn't work with uppercase y at the moment.

[Private internal link to relevant issue](https://github.com/appsignal/support/issues/204)

**Comment by jtmkrueger** [comment]
Okay @tombruijn, that time it sent the report and I got a URL, thanks!

**Comment by tombruijn** [comment]
@jtmkrueger do you still have the original issue of APPSIGNAL_APP_ENV not being picked up with the fix I explained in my comment https://github.com/appsignal/appsignal-nodejs/issues/704#issuecomment-1170860294? Let me know if we can close this issue.

**Comment by jtmkrueger** [comment]
@tombruijn I should be circling back on this issue soon, sorry for the delay.

**Comment by jtmkrueger** [comment]
https://appsignal.com/diagnose_reports/diag2458fee96a9fc970cc6d?linked=true
We installed python3, but still seeing a python3 error.

**Comment by tombruijn** [comment]
@jtmkrueger the installer says it can't find the `python3` executable in the PATH and the `python` executable is version `2.7.16`. Please make sure that the install path of python3 is available in the `PATH` env var and reinstall the AppSignal package. You can verify this manually by running `python3 --version` or `python --version` with it printing version 3.

**Comment by jtmkrueger** [comment]
We tried these things and it still doesn't seem to be able to find it.

**Comment by tombruijn** [comment]
We can jump on a call if you want to have a look. Please email us at support@appsignal.com. Mention this issue.

**Comment by tombruijn** [comment]
Closing
