### ISSUE TITLE
[issue] possible issue with opentelemetry on deployment

### ISSUE THREAD

**Issue by matoni109** [appsignal/appsignal-nodejs#811]
Hello appSignal 👋,

Just trying to bump to your `v3` node package, but I'm getting below which I think might be inherited from this [issue](https://github.com/open-telemetry/opentelemetry-js/issues/3448) over at OpenTelemetry:

```console
remote: =====> Start of platform-gateway-staging container output (web.1)        
remote:        > federation-gateway@0.1.2 start        
remote:        > doppler run -- node --require ./src/plugins/appsignal.cjs src/server.js        
remote:        no original function accessSync to wrap        
remote:        no original function appendFileSync to wrap        
remote:        no original function chmodSync to wrap        
remote:        no original function chownSync to wrap        
remote:        no original function copyFileSync to wrap        
remote:        no original function cpSync to wrap        
remote:        no original function existsSync to wrap        
remote:        no original function lchownSync to wrap        
remote:        no original function linkSync to wrap        
remote:        no original function lstatSync to wrap        
remote:        no original function lutimesSync to wrap        
remote:        no original function mkdirSync to wrap        
remote:        no original function mkdtempSync to wrap        
remote:        no original function opendirSync to wrap        
remote:        no original function openSync to wrap        
remote:        no original function readdirSync to wrap        
remote:        no original function readFileSync to wrap        
remote:        no original function readlinkSync to wrap        
remote:        no original function realpathSync to wrap        
remote:        no original function renameSync to wrap        
remote:        no original function rmdirSync to wrap        
remote:        no original function rmSync to wrap        
remote:        no original function statSync to wrap        
remote:        no original function symlinkSync to wrap        
remote:        no original function truncateSync to wrap        
remote:        no original function unlinkSync to wrap        
remote:        no original function utimesSync to wrap        
remote:        no original function writeFileSync to wrap        
remote:        no original function exists to wrap        
remote:        /app/node_modules/@opentelemetry/instrumentation-fs/build/src/instrumentation.js:53        
remote:                                if (instrumentation_1.isWrapped(fs.promises[fName])) {        
remote:                                                                           ^        
remote:        TypeError: Cannot read properties of undefined (reading 'access')        
remote:            at InstrumentationNodeModuleDefinition.patch (/app/node_modules/@opentelemetry/instrumentation-fs/build/src/instrumentation.js:53:68)        
remote:            at FsInstrumentation._onRequire (/app/node_modules/@opentelemetry/instrumentation/build/src/platform/node/instrumentation.js:79:35)        
remote:            at /app/node_modules/@opentelemetry/instrumentation/build/src/platform/node/instrumentation.js:133:29        
remote:            at /app/node_modules/@opentelemetry/instrumentation/build/src/platform/node/RequireInTheMiddleSingleton.js:54:27        
remote:            at Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:175:32)        
remote:            at require (node:internal/modules/cjs/helpers:102:18)        
remote:            at Object.<anonymous> (/app/node_modules/cacache/lib/entry-index.js:11:5)        
remote:            at Module._compile (node:internal/modules/cjs/loader:1112:14)        
remote:            at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)        
remote:            at Module.load (node:internal/modules/cjs/loader:988:32)        
remote:        Node.js v18.4.0        
```

```json
  "type": "module",
  "engines": {
    "node": "18.4.0",
    "yarn": "^1.22.19"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "eslint src/ -c .eslintrc --ext js",
    "start": "doppler run -- node --require ./src/plugins/appsignal.cjs src/server.js",
    "dev-start": "doppler run -- nodemon --require ./src/plugins/appsignal.cjs src/server.js"
  },
```
```js
// appsignal.cjs
const { Appsignal } = require('@appsignal/nodejs');

const appsignal = new Appsignal({
  active: process.env.NODE_ENV === 'production',
  name: `Platform Gateway`,
  revision: process.env.GIT_REV ? process.env.GIT_REV.slice(0, 7) : null,
  environment: process.env.LOG_ENV || 'development',
  pushApiKey: process.env.APPSIGNAL_PUSH_API_KEY,
});
```

**Comment by tombruijn** [comment]
Hi @matoni109, thanks for notifying us of this issue!

It looks like the same issue to me too. Looks like the fix has not been released yet in the OpenTelemetry packages.

You can disable the fs instrumentation from our end for now by configuring the [`disableDefaultInstrumentations`](https://docs.appsignal.com/nodejs/3.x/configuration/options.html#option-disabledefaultinstrumentations) option to `["@opentelemetry/instrumentation-fs"]` in the AppSignal config.

```js
// appsignal.cjs
const { Appsignal } = require("@appsignal/nodejs");
 
new Appsignal({
  // ...
  disableDefaultInstrumentations: ["@opentelemetry/instrumentation-fs"]
});
```

**Comment by tombruijn** [comment]
For the AppSignal team: let's wait until the next release is out and test if it's fixed by that.

- Reported upstream issue: https://github.com/open-telemetry/opentelemetry-js/issues/3448
- PR with fix: https://github.com/open-telemetry/opentelemetry-js/pull/3451

**Comment by matoni109** [comment]
Thanks @tombruijn,

We will wait for the next release, and then try and push to staging then, we couldn't get this to replicate in local dev.

**Comment by tombruijn** [comment]
We're going to remove the fs instrumentation by default in issue https://github.com/appsignal/appsignal-nodejs/issues/845 until this is resolved.

**Comment by tombruijn** [comment]
We removed the instrumentation default in package version 3.0.7. Please upgrade and let us know if it still happens.
